#include "robo-web-server.h"
#include "configs.h"
#include <Arduino.h>



uint8_t RoboWebServer::_servoPositions[16] = { 
    LA1_INITIAL_POSITION, LA2_INITIAL_POSITION , LA3_INITIAL_POSITION,
    RA1_INITIAL_POSITION, RA2_INITIAL_POSITION, RA3_INITIAL_POSITION,
    LH_INITIAL_POSITION, RH_INITIAL_POSITION, 
    LL1_INITIAL_POSITION, LL2_INITIAL_POSITION, LL3_INITIAL_POSITION,
    RL1_INITIAL_POSITION, RL2_INITIAL_POSITION, RL3_INITIAL_POSITION,
    LF_INITIAL_POSITION, RF_INITIAL_POSITION
};
